{% set name = "pyrfc3339" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/pyRFC3339/{{ name }}-{{ version }}.tar.gz
  sha256: e47843379ea35c1296c3b6c67a948a1a490ae0584edfcbdea0eaffb5dd29960b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - pytz

test:
  imports:
    - pyrfc3339
  commands:
    - pip check

about:
  home: https://github.com/kurtraschke/pyRFC3339
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python library for generating and parsing RFC 3339-compliant timestamps.'

  description: |
    pyRFC3339 parses and generates RFC 3339-compliant timestamps using 
    Python datetime.datetime objects.
  doc_url: https://pyrfc3339.readthedocs.io/
  dev_url: https://github.com/kurtraschke/pyRFC3339

extra:
  recipe-maintainers:
    - jan-janssen
