{% set name = "pyrfc3339" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/pyRFC3339/{{ name }}-{{ version }}.tar.gz
  sha256: c569a9714faf115cdb20b51e830e798c1f4de8dabb07f6ff25d221b5d09d8d7f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - pytz

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyrfc3339
  commands:
    - pip check

about:
  home: https://github.com/kurtraschke/pyRFC3339
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python library for generating and parsing RFC 3339-compliant timestamps.'

  description: |
    pyRFC3339 parses and generates RFC 3339-compliant timestamps using 
    Python datetime.datetime objects.
  doc_url: https://pyrfc3339.readthedocs.io/
  dev_url: https://github.com/kurtraschke/pyRFC3339

extra:
  recipe-maintainers:
    - jan-janssen
